# Generated by Django 5.2.2 on 2025-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_remove_question_created_at_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
