# Generated by Django 5.2.2 on 2025-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True),
        ),
    ]
